### ISSUE TITLE
Flixel-studio initialization and usage

### ISSUE THREAD

**Issue by al-arz** [Dovyski/flixel-studio#12]
First of all, let me thank you for all the time and effort you're putting into this tool. It's already useful and looks even more promising. I'm really happy someone is actually working on this :-)

Unfortunately, trying to start using flixel-studio I was slightly confused by what seems to be a contradiction between how it's supposed to behave and what it actually does.

The readme suggests you can put `FlxStudio.start()` into _any_ of your game's FlxState's. But since https://github.com/Dovyski/flixel-studio/commit/15e59b5162c4b1511ddf7951c5c57089e7ae55ba it looks like the actual initialization in `bootstrap()` function happens _only_ when the core engine's `gameStarted` signal is dispatched, which in turn happens _only once_ on game startup (well, on resets too, but I'm not sure if they're commonly used). That makes it neccessary to call `FlxStudio.start()` _at least_ in the initial game state (one that's passed as `FlxGame`'s constructor argument). On the other hand, calling `FlxStudio.start()` anywhere else doesn't have any effect (again, possibly except some corner cases with `FlxG.resetGame()`).

And I personally find this behaviour preferable to manually placing `FlxStudio.start()` everywhere you might need it. So probably that's just the docs that need to be updated. Unluckily, current implementation breaks entities inspector. Perhaps, flixel-studio needs a way to run some of its procedures (e.g. getting `_entities` list for EntitiesWindow) automatically after every state switch and _not_ in `bootstrap()`? That might require introducing something like `postStateCreate` signal into the core, but that should be trivial.

So, before I make any PR's, which I'd do gladly, is there anything I'm missing here?

**Comment by Dovyski** [comment]
> First of all, let me thank you for all the time and effort you're putting into this tool. It's already useful and looks even more promising. I'm really happy someone is actually working on this :-)

Thank you very much! I am very happy to see the feedback the tool is receiving, like your suggestions and comments :)

> And I personally find this behaviour preferable to manually placing `FlxStudio.start()` everywhere you might need it. So probably that's just the docs that need to be updated. Unluckily, current implementation breaks entities inspector. Perhaps, flixel-studio needs a way to run some of its procedures (e.g. getting `_entities` list for EntitiesWindow) automatically after every state switch and _not_ in `bootstrap()`? That might require introducing something like `postStateCreate` signal into the core, but that should be trivial.

My initial idea was to force developers to manually place `FlxStudio.start()` everywhere they neet it. It makes things "less magic" because you know what and where things are happening. However, as you described, calling `FlxStudio.start()` once is not a bad idea too. It makes things easier if we had a `postStateCreate` to monitor state changes. I would like to know your opinion on why placing a single `FlxStudio.start()` is ideal.

Regarding components data in flixel-studio, e.g. `_entities`, when I first envisioned the architecture currently in use, the `bootstrap()` method would initialize all inner components of flixel-studio, i.e. `EntitiesWindow` or `_entities`, if they were not previously initialized. If they were already (`bootstrap()` is being called because of a state reset), then the method would invoke something like `refresh()` on each component, forcing them to fetch new data to reflect the current state of the game. I haven't implemented any refresh mechanism at the moment though.

Deleting and recreating all components is not ideal either, because in the near future flixel-studio will keep data in memory regarding user actions, e.g. level edits, adjustments, etc. We need to be able to use such data after a state reset, otherwise flixel-studio will lose context of what is happening.

P.S. Sorry for the late reply, I've moved recently, so my schedule/time is a mess.

**Comment by Geokureli** [comment]
Came here to say something similar: `start()` needs to be called at a specific spot and it seems like the entity display does not update with state changes. When I tested this on the Mode demo I would have to make the PlayState the initial state to get this to work. Currently, when I call start on MenuState, and switch to PlayState the entities window list reflects the objects in MenuState

I second then notion to have devs call `start()` once and have Flixel-Studio track state changes to always show the current state's entities.

I've finally gotten around to checking this repo out, and it has potential, thanks again for starting this!

**Comment by Dovyski** [comment]
Thanks for the feedback @Geokureli ! Calling `start()` once is indeed a good approach, I will work towards making that happen. In such case, I think a method name like `embed()` or `init()` is better and more descriptive than `start()`. For me, "start" implies something that repeats over time.

> I've finally gotten around to checking this repo out, and it has potential, thanks again for starting this!

Awesome, thank you! 😄

**Comment by Geokureli** [comment]
I've gone ahead and tried to make a basic test branch that updates the entities on state changes and while it's not thoroughly tested yet, it's working pretty well!

https://github.com/Dovyski/flixel-studio/compare/master...Geokureli:track_state_changes?expand=1
Note: to try this I had to add `FlxG.signals.postStateSwitch` to the flixel dev branch, which is currently pending approval.
https://github.com/HaxeFlixel/flixel/pull/2207

**Comment by Dovyski** [comment]
It looks awesome, great work! As soon as your PR is merged into Flixel, we can bring your changes to Flixel Studio as well.

**Comment by Dovyski** [comment]
Commit 91af9abdac21ec477453297a4df4ed55a981ffa9 deals with the entity list update when the state changes and the call of `start()` once. I think it solves this issue, so I'm closing it. Feel free to continue the discussion if you want to add/suggest/clarify anything.

**Comment by al-arz** [comment]
Sorry for my recent absence, my last few weeks were somewhat messy as well.
Glad that Geokureli came and actually wrote some code and didn't let anybody get too deep into the discussion :)
I still have some design questions though, but that's for other topics.
